export const SET_TURN = 'App/SET_TURN';
export const INCREMENT_TURN = 'App/INCREMENT_TURN';
export const DECREMENT_TURN = 'App/DECREMENT_TURN';
export const REQUEST_DATA = 'App/REQUEST_DATA';
export const ADD_NOTE_LIST = 'APP/ADD_NOTE_LIST';
export const REMOVE_NOTE_LIST = 'APP/REMOVE_NOTE_LIST';
export const ADD_NOTE_LIST_DETAIL = 'APP/ADD_NOTE_LIST_DETAIL';
export const REMOVE_NOTE_LIST_DETAIL = 'APP/REMOVE_NOTE_LIST_DETAIL';
